baseURL = 'www.ultras.ma'
languageCode = 'en-us'
title = 'ultras maroc'
canonifyURLs = true
publishDir = 'docs'
relativeURLs = true
[taxonomies]
   tag = "tags"
   category = "categories"
   price = "prices"
   image = "images"